#!/usr/bin/env bash
# Formal verification gate for the eh module (Frama-C).
#
#   1. WP  - deductive proof of the ACSL contracts that describe the answer
#      the module builds (zk_eh_fill_phdrs, zk_eh_extent, zk_eh_build_info),
#      with RTE guards. Fails unless every goal is discharged.
#   2. Eva - value analysis of the two drivers, which run the module end to
#      end, dispatcher included, in both shapes an image can have: unwind
#      tables kept (eva_main.c) and stripped (eva_main_stripped.c). Fails on
#      any alarm or any logical property left unknown or invalid.
#
# The split is not cosmetic: WP cannot reason about a call through a
# caller-supplied function pointer, which is all __wrap_dl_iterate_phdr does
# after building the block. Eva resolves that pointer against the driver's
# callback and covers the dispatcher, so every line of the module is verified
# by one analysis or the other.
#
# Usage: ./run_wp.sh
#   FRAMAC=<frama-c binary>        (default: frama-c)
#   WP_TIMEOUT=<seconds per goal>  (default: 60)
#
# Locally (needs docker):
#   docker run --rm -v "$PWD":/w -w /w framac/frama-c:30.0 \
#       src/bflat/modules/eh/verify/run_wp.sh
#
# Copyright (C) 2026 Demerzel Solutions Limited (Nethermind)
#
# Author: Maxim Menshikov <maksim.menshikov@nethermind.io>

set -uo pipefail

VERIFY_DIR="$(cd "$(dirname "$0")" ; pwd -P)"
MODULE_DIR="$(dirname "${VERIFY_DIR}")"

FRAMAC="${FRAMAC:-frama-c}"
WP_TIMEOUT="${WP_TIMEOUT:-60}"
NPROC="$(nproc 2>/dev/null || echo 4)"

# The functions that build the answer. The dispatcher is deliberately absent:
# see the header comment.
WP_FCTS="zk_eh_fill_phdrs,zk_eh_extent,zk_eh_build_info"

command -v "${FRAMAC}" > /dev/null 2>&1 || {
	echo "error: frama-c not found (apt install frama-c, or use the docker image)" >&2
	exit 1
}

fail=0

echo "=== WP: deductive verification of ACSL contracts ==="
wp_out=$("${FRAMAC}" -wp -wp-rte -wp-timeout "${WP_TIMEOUT}" -wp-par "${NPROC}" \
	-machdep gcc_x86_64 -wp-fct "${WP_FCTS}" "${MODULE_DIR}/module.c" 2>&1)
wp_status=$?
echo "${wp_out}" | grep -E "Proved goals|Qed:|Alt-Ergo|Timeout|Failed|Unknown" | head -20

proved=$(echo "${wp_out}" \
	| sed -n 's/.*Proved goals:[[:space:]]*\([0-9][0-9]*\)[[:space:]]*\/[[:space:]]*\([0-9][0-9]*\).*/\1 \2/p')
ok=$(echo "${proved}" | awk '{print $1}')
total=$(echo "${proved}" | awk '{print $2}')

if [ "${wp_status}" -ne 0 ] || [ -z "${ok}" ] || [ -z "${total}" ] || \
   [ "${ok}" != "${total}" ] || [ "${total}" = "0" ] ; then
	echo "WP: FAILED (proved ${ok:-?}/${total:-?} goals)" >&2
	fail=1
else
	echo "WP: OK - all ${total} goals proved"
fi

for driver in eva_main.c eva_main_stripped.c ; do
	echo ""
	echo "=== Eva: absence of runtime errors (${driver}) ==="
	eva_out=$("${FRAMAC}" -eva -eva-precision 2 -machdep gcc_x86_64 \
		"${VERIFY_DIR}/${driver}" 2>&1)
	eva_status=$?
	echo "${eva_out}" | grep -E "alarms generated|Assertions|Preconditions" | head -10

	if [ "${eva_status}" -ne 0 ] || \
	   ! echo "${eva_out}" | grep -q "0 alarms generated by the analysis" ; then
		echo "Eva: FAILED (alarms or analysis error) [${driver}]" >&2
		fail=1
	elif echo "${eva_out}" | grep -qE "[1-9][0-9]* (unknown|invalid)" ; then
		echo "Eva: FAILED (unknown or invalid logical properties) [${driver}]" >&2
		fail=1
	else
		echo "Eva: OK - no alarms, all properties proven"
	fi
done

exit ${fail}
